"""initial schema

Revision ID: 45f3346af8db
Revises: 
Create Date: 2026-08-30 22:17:54.542423
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '45f3346af8db'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='user_role', native_enum=False, length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_email', sa.String(length=320), nullable=True),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('target_label', sa.String(length=320), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_action_created', 'audit_events', ['action', 'created_at'], unique=False)
    op.create_index('ix_audit_created', 'audit_events', ['created_at'], unique=False)
    op.create_index('ix_audit_owner_created', 'audit_events', ['owner_user_id', 'created_at'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('display_name', sa.String(length=240), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_sessions_owner', 'user_sessions', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_user_sessions_refresh_token_hash'), 'user_sessions', ['refresh_token_hash'], unique=False)
    op.create_index('ix_user_sessions_revoked', 'user_sessions', ['revoked_at'], unique=False)
    op.create_table('voximplant_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('api_host', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('access_token_ciphertext', sa.Text(), nullable=False),
    sa.Column('access_token_iv', sa.String(length=32), nullable=False),
    sa.Column('access_token_auth_tag', sa.String(length=32), nullable=False),
    sa.Column('access_token_key_version', sa.Integer(), nullable=False),
    sa.Column('access_token_fingerprint', sa.String(length=16), nullable=True),
    sa.Column('access_token_rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('last_connection_status', sa.Enum('UNKNOWN', 'CONNECTED', 'DISCONNECTED', 'INVALID_CREDENTIALS', 'ERROR', name='connection_status', native_enum=False, length=32), nullable=False),
    sa.Column('last_connection_error', sa.String(length=512), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_name', sa.String(length=255), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'api_host', 'domain', name='uq_connection_owner_host_domain')
    )
    op.create_index('ix_connections_owner', 'voximplant_connections', ['owner_user_id'], unique=False)
    op.create_index('ix_connections_owner_default', 'voximplant_connections', ['owner_user_id', 'is_default'], unique=False)
    op.create_table('transcription_queue_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'PROCESSING', 'DONE', 'FAILED', 'SKIPPED', 'CANCELED', name='queue_item_status', native_enum=False, length=16), nullable=False),
    sa.Column('whisper_model', sa.String(length=32), nullable=False),
    sa.Column('record_url', sa.Text(), nullable=True),
    sa.Column('datetime_start', sa.String(length=64), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('caller_a', sa.String(length=64), nullable=True),
    sa.Column('caller_b', sa.String(length=64), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('scenario_name', sa.String(length=255), nullable=True),
    sa.Column('transcript_text', sa.Text(), nullable=True),
    sa.Column('audio_filename', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['voximplant_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'connection_id', 'call_id', name='uq_queue_owner_conn_call')
    )
    op.create_index('ix_queue_owner_status', 'transcription_queue_items', ['owner_user_id', 'status'], unique=False)
    op.create_index('ix_queue_status_created', 'transcription_queue_items', ['status', 'created_at'], unique=False)
    op.create_table('transcription_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('weekdays', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('from_hour', sa.Integer(), nullable=False),
    sa.Column('to_hour', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.Column('min_duration', sa.Integer(), nullable=False),
    sa.Column('has_recording', sa.Boolean(), nullable=False),
    sa.Column('records_limit', sa.Integer(), nullable=False),
    sa.Column('whisper_model', sa.String(length=32), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_slot', sa.String(length=64), nullable=True),
    sa.Column('last_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['voximplant_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_schedules_owner', 'transcription_schedules', ['owner_user_id'], unique=False)
    op.create_table('transcripts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.String(length=128), nullable=False),
    sa.Column('record_url_hash', sa.String(length=64), nullable=True),
    sa.Column('transcript_text', sa.Text(), nullable=False),
    sa.Column('whisper_model', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('audio_filename', sa.String(length=255), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('datetime_start', sa.String(length=64), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('phone_a', sa.String(length=64), nullable=True),
    sa.Column('phone_b', sa.String(length=64), nullable=True),
    sa.Column('scenario_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['voximplant_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'connection_id', 'call_id', name='uq_transcript_owner_conn_call')
    )
    op.create_index('ix_transcripts_owner_created', 'transcripts', ['owner_user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_transcripts_record_url_hash'), 'transcripts', ['record_url_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcripts_record_url_hash'), table_name='transcripts')
    op.drop_index('ix_transcripts_owner_created', table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index('ix_schedules_owner', table_name='transcription_schedules')
    op.drop_table('transcription_schedules')
    op.drop_index('ix_queue_status_created', table_name='transcription_queue_items')
    op.drop_index('ix_queue_owner_status', table_name='transcription_queue_items')
    op.drop_table('transcription_queue_items')
    op.drop_index('ix_connections_owner_default', table_name='voximplant_connections')
    op.drop_index('ix_connections_owner', table_name='voximplant_connections')
    op.drop_table('voximplant_connections')
    op.drop_index('ix_user_sessions_revoked', table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_refresh_token_hash'), table_name='user_sessions')
    op.drop_index('ix_user_sessions_owner', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_table('user_profiles')
    op.drop_index('ix_audit_owner_created', table_name='audit_events')
    op.drop_index('ix_audit_created', table_name='audit_events')
    op.drop_index('ix_audit_action_created', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
